### ISSUE TITLE
What does AT-23, AT-20, AT-04,... mean?

### ISSUE THREAD

**Issue by ThomasLandauer** [smhg/sepa-qr-data-php#1]
See e.g. https://github.com/smhg/sepa-qr-data-php#setbicbic
I figure you've copied this from the EPC PDF. Do you know what it stands for?

**Comment by smhg** [comment]
Not sure, but it seems to be the identifier of each part of the money transfer? Maybe it predates SEPA? Feel free to add it to this issue if you figure it out. It would be nice to know.

**Comment by ThomasLandauer** [comment]
From the "SCT Rulebook" at https://www.europeanpaymentscouncil.eu/document-library/rulebooks/2019-sepa-credit-transfer-rulebook-version-12 :

> This numbering is only for cross referencing purposes within the Rulebook.

So I would suggest: Remove it from README; since "AT-23" is just a shortcut for "The BIC code of the Beneficiary Bank" and doesn't add any value.

**Comment by smhg** [comment]
Thank you for looking this up!
