### ISSUE TITLE
BIC code format check is incorrect

### ISSUE THREAD

**Issue by AegisVP** [smhg/sepa-qr-data-php#11]
BIC code can be either 8 characters long **or** 11 characters long

SepaQr\Data->setBic($bic) allows BIC code to be from 8 to 11 characters long (9 and 10 character long codes are invalid).
ref: [https://www.swift.com/standards/data-standards/bic-business-identifier-code](https://www.swift.com/standards/data-standards/bic-business-identifier-code)

**Comment by AegisVP** [comment]
PR #12 addresses this issue

**Comment by smhg** [comment]
Good catch, thanks!
