### ISSUE TITLE
Wrong QR payment code image

### ISSUE THREAD

**Issue by fafayqa** [smhg/sepa-qr-data-php#13]
```
<?php

require_once('vendor/autoload.php');

use SepaQr\Data;
use chillerlan\QRCode\QRCode;
use chillerlan\QRCode\QROptions;

$paymentData = Data::create()
  ->setName('Name of the beneficiary')
  ->setIban('BE123456789123456789')
  ->setAmount(100); // The amount in Euro

$qrOptions = new QROptions([
    'eccLevel' => QRCode::ECC_H // required by EPC standard
]);

(new QRCode($qrOptions))->render($paymentData, 'payment.png');
?>
```

When I generate the QR with your the above code and let my smartphone bank app scan it it says wrong QR code, not payment QR code! I am in Slovakia (EU), using MBank mobile app and its internal QR payment function (it can scan real QR payment codes on regular basis with no problem).

**Comment by smhg** [comment]
@fafayqa it might be a different standard is used among those apps/banks. Something similar happens with Payconiq in Belgium.

Can you scan the example on wikipedia with your bank app?
https://en.wikipedia.org/wiki/EPC_QR_code

**Comment by fafayqa** [comment]
I tried both QR images there and both produced exactly the same wrong QR payment image as with your code.

BTW this string produces correct QR payment code image (I guess it is in base64 format, produced by QrPaymentSR lib):

0004U0001M8GLP3E8KPT058IQ99QISMB02IH36MOD4BCKQQGVDE4641AOA2NURPCOPSALFG0LPG1C6N0E2JMC7RG2F4L2E57OCSHOUROGHOC8VTTPHHRFHU6VFTM8N80

**Comment by smhg** [comment]
Seems like you need another format then (not SEPA standard).
You can always ask you bank if they plan to support this. Maybe they take it into account in future versions.

**Comment by fafayqa** [comment]
Oh, I thought maybe adding option to convert the final string to base64 could help...just saying judging from the experience (tho maybe not, who knows).
