### ISSUE TITLE
add test with different encoding

### ISSUE THREAD

**Issue by ThomasLandauer** [smhg/sepa-qr-data-php#3]
The data I'm passing contains only ASCII characters. And my PHP file is UTF-8.

However, when I do `->setCharacterSet(SepaQrData::UTF_8)` it doesn't work (at least with the banking app I'm trying), but when I do `->setCharacterSet(SepaQrData::ISO8859_1)`, it does. Why?
And why is the QR code changing at all? And does this setting have to be the same as the setting you pass to endroid/qr-code, or does one (which?) override the other or doesn't it matter?

**Comment by smhg** [comment]
Good question! I haven't tried anything other than UTF-8 myself. We'll need to a test for this.
You'll definitely have to change endroid/qr-code's encoding too:

```php
// ...
use Endroid\QrCode\Encoding\Encoding;
// ...

Builder::create()
  ->encoding(new Encoding('ISO-8859-1'))
  // ->...
```

**Comment by smhg** [comment]
I've been thinking about this a bit more. But I can't find a way to add a test that makes sense.
It would require adding tests with a/some QR rendering libraries. I don't know how to make that work across different PHP versions.

**Comment by smhg** [comment]
I'm going to close this as encoding is 99% related to the surrounding parts of where you use this library.
Setting a character set with `setCharacterSet` only adds the appropriate identifier so the consumer of the data (decoding the QR code) can act accordingly.
