### ISSUE TITLE
improve readme to highlight use with qr code libraries

### ISSUE THREAD

**Issue by smhg** [smhg/sepa-qr-data-php#4]
Clarify that:
- The output of this project is always an intermediary step.
- Needs to be used with e.g.
  - endroid/qr-code
  - chillerlan/php-qrcode
  - milon/barcode
  - bacon/bacon-qr-code (?)

**Comment by smhg** [comment]
@ThomasLandauer I've split up the readme as much as I think is sensible.
Ideally, a simple website with proper step-by-step information would be better. But this will need to do.

**Comment by ThomasLandauer** [comment]
IMO, you don't need more explanations (or another website). You have copy-pastable code for 2 QR libraries - what can people expect more?

More important (IMO): Show the code, show the code, show the code :-)
```
BCD
002
1
SCT
Name of the beneficiary
BE123456789123456789
EUR100.00
```
Just add it to README somewhere, and everybody is happy ;-)
