### ISSUE TITLE
Add rounded border to the QR code

### ISSUE THREAD

**Issue by ThomasLandauer** [smhg/sepa-qr-data-php#8]
There's a "standard" in Austria to add a rounded border with some text in it, around the QR code - see https://www.stuzza.at/de/zahlungsverkehr/qr-code.html
It looks like in Germany they have this too: https://www.girocode.de/girocodetools/pages/girosolution/ and on https://en.wikipedia.org/wiki/EPC_QR_code some other countries are mentioned as well.

I already suggested this at https://github.com/endroid/qr-code/issues/313 - just mentioning this here in case somebody is interested... ;-)

**Comment by smhg** [comment]
From experience, to increase adoption it definitely helps to have such a label with the QR code. Good to know it exists!
However, the visual part (QR code) is (now) entirely outside the scope of this project.
