### ISSUE TITLE
Multiple currencies

### ISSUE THREAD

**Issue by mjohndus** [smhg/sepa-qr-data-php#9]
Very informative. I have not dealt with sepa before.
But I noticed one small problem.
My bank app (Revolut: bank with multiple currencies and my account in Euro) did not accept the qr-code without amount. I found out that the missing currency is responsible for this.

Changing the line:
- $values['amount'] > 0 ? formatMoney($values['amount']) : '',
to
- $values['amount'] > 0 ? formatMoney($values['amount']) : 'EUR',

to specify the currency without amount solved it. But I was still not satisfied.
After creating the function "setCurrency" and other additions, you can now choose between several currencies.
Some other changes (preg_replace...) are only for demonstration and/or are alternatives to aborts. Checks could also be done before commit.

Have a look at it on:
[Multiple currencies](https://github.com/mjohndus/sepa-qr-data-php/blob/master/src/Data.php)

**Comment by smhg** [comment]
@mjohndus Thank you for your contribution!
I think these are definitely great to have:

- proper handling of missing amount
- support for multiple currencies

I'd be happy to merge these if you can send separate PRs with tests for these.
I'll also leave some comments on your fork, but please don't submit all these changes. Create separate commits on separate branches with separate PRs for the above features if you can.

**Comment by mjohndus** [comment]
It was not my intention to change your code. It was just an idea and there was a lot of playing around. But I'll give it some thought and report back to you.
Note: Its only Hobby for me and excuse my English.

**Purpose codes:**
These are 4 capital letters (text keys) that indicate the reason for the transfer. They are often included in the reference.
[purpose codes 1](https://www.hettwer-beratung.de/sepa-spezialwissen/sepa-technische-anforderungen/sepa-purpose-codes-vs-dta-textschl%C3%BCssel/)
[purpose codes 2](https://www.fs-bank.de/content/dam/f1131-0/webn/sepa_mustervorlagen/uebersicht_purpose_codes.pdf)

**I have created 2 new branches.**
[EURO2](https://github.com/mjohndus/sepa-qr-data-php/tree/euro2)  
is another solution for my app problem.  
and  
[sepaqr](https://github.com/mjohndus/sepa-qr-data-php/tree/sepaqr)  
support for multiple currencies + tests

**Comment by smhg** [comment]
Thank you for the links to the purpose codes! That's very useful.
Feel free to send PR's once you think something is ready to share with others.

**Comment by mjohndus** [comment]
I changed the link above.
[sepaqr](https://github.com/mjohndus/sepa-qr-data-php/tree/sepaqr)
Take a look.

**Comment by smhg** [comment]
Please send a PR from a separate branch containing 1 feature/fix. That allows me to compare the new code to the existing code. Browsing through your branches and commits is not very efficient.

**Comment by smhg** [comment]
I've added the setter for the currency myself. I will close this issue as this feature is now available, but feel free to send PR's with any improvement you can think of.
